server:
  port: 18082
spring:
   datasource:
       url: jdbc:mysql://192.168.0.37:3306/goldbuy?useSSL=false&allowMultiQueries=true
       username: root
       password: 111111
       driver-class-name: com.mysql.jdbc.Driver
       hikari:
          maximum-pool-size: 15
          connection-timeout: 60000
   redis:
     cluster:
       nodes: 192.168.0.99:7001,192.168.0.99:7002,192.168.0.99:7003,192.168.0.99:7004,192.168.0.99:7005,192.168.0.99:7006
     timeout: 10000ms
     lettuce:
       pool:
         max-active: 100
         min-idle: 10
         max-wait: 10000ms
dubbo:
    service:
      version: 1.0.0 #定义项目版本
    scan:
       basePackages: com.goldeasy.user.service.impl #调用dubbo组建扫描的项目路径
    application:
      id: goldeasy-user-service #注册在注册中心的名称，唯一标识，请勿重复
      name: goldeasy-user-service #注册在注册中心的名称，唯一标识，请勿重复
      qos-enable: false
    protocol:
      port: 30001 #暴露服务端口 （默认是20880，修改端口，不同的服务提供者端口不能重复）
      retries: 1 #远程服务调用重试次数，不包括第一次调用，不需要重试请设为0，默认2
      timeout: 120000
      name: dubbo #默认名称，勿修改
    registry:
      id: zookeeper-registry
      address: zookeeper://192.168.0.100:2182?backup=192.168.0.100:2183,192.168.0.100:2184

mybatis:
  mapper-locations: classpath:com/goldeasy/*/mapping/*.xml
userInfo:
  generalManagerId: 111111
  marketingDirectorId: 222222
  managerId: 333333
  directorId: 444444
  brokerId: 555555

ossConfig:
  endpoint: 11111
  accessKeyId: 222222
  accessKeySecret: 33333
  bucketName: 44444
